### ISSUE TITLE
Upload using wildcard and to root of container

### ISSUE THREAD

**Issue by gungorbudak** [fixpoint/azblob-upload-artifact#7]
Hi, 

Is it possible to upload using wildcards like in [this](https://github.com/actions/upload-artifact#upload-using-a-wildcard-pattern) and below configuration?

```
      - name: Upload app to Azure storage
        uses: fixpoint/azblob-upload-artifact@v3
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container: "downloads"
          name: dist
          path: dist/*.{exe,blockmap,AppImage,pkg,yml}
```

Also, with below configuration it uploads dist directory content but is it possible that it uploads to the root of the container like `downloads/` instead of `downloads/dist/`? 

```
      - name: Upload app to Azure storage
        uses: fixpoint/azblob-upload-artifact@v3
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container: "downloads"
          name: dist
          path: dist
```

Thanks
